const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

/**
 * Ensures Android has a splashscreen_logo drawable so the build does not fail
 * when app.json splash has no image. Writes a minimal drawable (same as background)
 * so the splash screen shows only the background color with no visible logo.
 */
function withSplashScreenLogo(config) {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const drawableDir = path.join(
        projectRoot,
        'android',
        'app',
        'src',
        'main',
        'res',
        'drawable'
      );
      const drawablePath = path.join(drawableDir, 'splashscreen_logo.xml');
      const content = `<?xml version="1.0" encoding="utf-8"?>
<!-- Empty splash logo: same as background so no visible image (generated by withSplashScreenLogo plugin) -->
<shape xmlns:android="http://schemas.android.com/apk/res/android"
  android:shape="rectangle">
  <solid android:color="@color/splashscreen_background" />
  <size android:width="1dp" android:height="1dp" />
</shape>
`;
      await fs.promises.mkdir(drawableDir, { recursive: true });
      await fs.promises.writeFile(drawablePath, content, 'utf8');
      return config;
    },
  ]);
}

module.exports = withSplashScreenLogo;
